### ISSUE TITLE
Should return isSupported false if Play Services is not available

### ISSUE THREAD

**Issue by augustresende** [CodesFirst/grecaptcha#1]

**Comment by pewiher** [comment]
Added logic for isSupported and added a new googlePlayServicesAvailability method that returns :

`GooglePlayServicesAvailability.success`
`GooglePlayServicesAvailability.serviceMissing`
`GooglePlayServicesAvailability.serviceUpdating`
`GooglePlayServicesAvailability.serviceVersionUpdateRequired`
`GooglePlayServicesAvailability.serviceDisabled`
`GooglePlayServicesAvailability.serviceInvalid`


avaliable version 0.0.6
